/** Recompute every value in the distributable validation report. No stored reference run is used. */
import { mkdir, writeFile } from 'node:fs/promises';
import { Thermodynamics } from '../src/thermo.js';
import { rachfordRice } from '../src/numerics.js';
import { demoProject, emptyProject, createNode } from '../src/model.js';
import { COMPONENTS } from '../src/components.js';
import { simulate, sensitivity } from '../src/simulator.js';
const root=new URL('../',import.meta.url);
await mkdir(new URL('docs/',root),{recursive:true});await mkdir(new URL('examples/',root),{recursive:true});
const write=(name,text)=>writeFile(new URL(name,root),text);
const json=(name,data)=>write(name,JSON.stringify(data,null,2)+'\n');
const p=demoProject(),r=simulate(p);
const s=sensitivity(p,{node:'flash',parameter:'T',min:363.15,max:372.15,points:13,stream:'VAPOR',metric:'F'});
const thermo=new Thermodynamics(['benzene','toluene']);
const f=thermo.flashTP(100,[.5,.5],368.15,101325);
const ph=thermo.flashPH(f.F,f.z,f.P,f.h);
const water=new Thermodynamics(['water']);const Ts=370,Ps=water.psat(0,Ts);
const pure=water.flashPH(10,[1],Ps,.6*water.hL(0,Ts,Ps)+.4*water.hV(0,Ts));
const checks=[];
function check(name,actual,expected,tolerance){const error=Math.abs(actual-expected),passed=error<=tolerance;checks.push({name,actual,expected,absoluteError:error,tolerance,passed});if(!passed)process.exitCode=1;}
check('Rachford–Rice: z=[0.5,0.5], K=[2,0.5]',rachfordRice([.5,.5],[2,.5]).beta,.5,1e-12);
check('Mixture TP → PH temperature, K',ph.T,368.15,1e-7);
check('Pure water PH latent plateau temperature, K',pure.T,370,1e-7);
check('Pure water PH latent plateau vapor fraction',pure.beta,.4,1e-12);
check('Default process product flow, mol/s',r.diagnostics.productFlow,100,1e-7);
check('Default process global mass residual, kg/s',r.diagnostics.globalMassResidual,0,1e-8);
check('Default process global energy residual, W',r.diagnostics.globalEnergyResidual,0,1e-3);
check('Default process scaled recycle residual',r.diagnostics.recycleResidual,0,1e-8);
check('Default process scaled balance residual',r.diagnostics.balanceResidual,0,1e-8);
function simple(type,cfg){
  const q=emptyProject(),feed=createNode('feed',70,180,q.components),unit=createNode(type,350,180,q.components),product=createNode('product',650,180,q.components);
  Object.assign(feed,{id:'feed',tag:'FEED'});Object.assign(feed.cfg,{F:100,z:{benzene:.5,toluene:.5}});
  Object.assign(unit,{id:'unit',tag:type.toUpperCase()});Object.assign(unit.cfg,cfg);Object.assign(product,{id:'product',tag:'PRODUCT'});
  q.name=type==='heater'?'Sensible heater benchmark':'Liquid pump benchmark';q.nodes=[feed,unit,product];q.streams=[{id:'in',tag:'IN',kind:'material',from:{node:'feed',port:'out'},to:{node:'unit',port:'in'}},{id:'out',tag:'OUT',kind:'material',from:{node:'unit',port:'out'},to:{node:'product',port:'in'}}];return q;
}
const hp=simple('heater',{T:348.15}),hr=simulate(hp);
check('Sensible heater Q = F Cp ΔT, W',hr.blocks.unit.Q,146050,1e-5);
const pp=simple('pump',{P:301325,efficiency:.8}),pr=simulate(pp);
check('Liquid pump W = F v ΔP / η, W',pr.blocks.unit.W,100*(.5*.0781118/874+.5*.0921384/867)*200000/.8,1e-7);
await json('examples/aromatics-recovery.vapora.json',p);await json('examples/sensible-heater.vapora.json',hp);await json('examples/liquid-pump.vapora.json',pp);
await json('examples/aromatics-recovery.results.json',{project:p,results:r});await json('examples/flash-temperature-sensitivity.json',s);
await json('docs/numerical-validation.json',{checks,passed:checks.filter(c=>c.passed).length,diagnostics:r.diagnostics,method:p.method,assumptions:'IDEAL-RAOULT; constant Cp, latent heat anchors and liquid densities. Internal equation verification, not plant validation.'});
const fmt=(n,d=9)=>Number.isFinite(n)?n.toPrecision(d):String(n);
const md=`# Numerical validation\n\nGenerated by \`npm run validate\` from the engine in this archive. These are freshly calculated values, not UI fixtures. A test that passes establishes agreement with the stated equations, not commercial-simulator or experimental accuracy.\n\n## Analytical and conservation checks\n\n| Check | Actual | Expected | Absolute error | Allowed error |\n|---|---:|---:|---:|---:|\n${checks.map(c=>`| ${c.name} | ${fmt(c.actual)} | ${fmt(c.expected)} | ${fmt(c.absoluteError,4)} | ${c.tolerance} |`).join('\n')}\n\n**${checks.filter(c=>c.passed).length}/${checks.length} generated checks passed.** The separate \`npm test\` suite covers unit conversion, endpoints, invalid inputs, all unit-operation types, explicit energy coupling, pure-component saturation, two simultaneous recycle tears, sensitivity failures, serialization, and undo/redo.\n\n## Aromatics recovery\n\nFresh feed: 100 mol/s; benzene/toluene mole fractions 0.55/0.45; 338.15 K; 101325 Pa. Pump discharge 300000 Pa and efficiency 0.75. Heater outlet 373.15 K. Valve and drum pressure 101325 Pa. Drum temperature 368.15 K. The liquid split sends 35% to product and 65% through a cooler at 338.15 K and a recycle tear.\n\n| Stream | Flow, mol/s | T, K | P, Pa | Vapor fraction | Benzene mole fraction |\n|---|---:|---:|---:|---:|---:|\n${p.streams.filter(e=>e.kind==='material').map(e=>{const a=r.streams[e.id];return `| ${e.tag} | ${fmt(a.F)} | ${fmt(a.T)} | ${fmt(a.P)} | ${fmt(a.beta)} | ${fmt(a.z[0])} |`;}).join('\n')}\n\nStatus: **${r.status}**, ${r.iterations} iterations. Scaled recycle residual: ${fmt(r.diagnostics.recycleResidual)}. Scaled global balance residual: ${fmt(r.diagnostics.balanceResidual)}.\n\nNet heat into all material operations: ${fmt(r.diagnostics.totalQ)} W. Shaft power input: ${fmt(r.diagnostics.totalW)} W. Exported cooler heat: ${fmt(r.streams['Q-102'])} W. All component and unit energy residuals are included in the JSON results. Numerical timings depend on the host and are not a performance guarantee.\n\n## Independently solved sensitivity points\n\n| Drum T, °C | Vapor flow, kmol/h | Status | Iterations |\n|---|---:|---|---:|\n${s.rows.map(a=>`| ${(a.value-273.15).toFixed(2)} | ${a.y==null?'—':(a.y*3.6).toFixed(6)} | ${a.status} | ${a.iterations??'—'} |`).join('\n')}\n\n## Browser coverage\n\n\`tests/browser-smoke.py\` exercises the real bundled Worker, changes specifications, reconnects blocks, solves a newly created model, runs sensitivity, converts temperature units, drags and deletes nodes, restores topology with undo/redo, and imports a project file. See \`browser-validation.json\` for the executed checks.\n\nThe browser test uses an opaque about:blank context and the **Canvas 2D fallback**. The WebGPU code path is implemented but was **not runtime-validated or hardware-benchmarked in the delivery environment**. Test the WebGPU backend on a supported browser served from localhost or HTTPS before deployment.\n\n## Verification boundary\n\nThe Antoine coefficient test checks transcription and evaluation. The approximate normal-boiling check is not a full vapor-pressure validation. Constant heat-capacity, vaporization-enthalpy and density assumptions have not been calibrated against plant data. No comparison to Aspen Plus results is asserted.\n`;
await write('docs/VALIDATION.md',md);
const componentRows=COMPONENTS.map(c=>`| ${c.name} | ${c.antoine.A} | ${c.antoine.B} | ${c.antoine.C} | ${c.antoine.Tmin}–${c.antoine.Tmax} |`).join('\n');
await write('docs/COMPONENT-DATA.md',`# Component model constants\n\nPressure from the listed Antoine coefficients is in bar; temperature is in kelvin. The engine converts pressure to pascals. Only these single, continuous coefficient sets are used.\n\n| Species | A | B | C | Published Antoine interval, K |\n|---|---:|---:|---:|---|\n${componentRows}\n\n## Rounded caloric and density assumptions\n\nThese constants are explicit **engineering approximations**, not a copied NIST caloric database. They must be replaced or regressed for higher-fidelity prediction.\n\n| Species | MW, kg/mol | Cp liquid, J/mol K | Cp vapor, J/mol K | Tb anchor, K | ΔHvap anchor, J/mol | Liquid density, kg/m³ | Tc guard, K |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${COMPONENTS.map(c=>`| ${c.name} | ${c.MW} | ${c.cpL} | ${c.cpV} | ${c.Tb} | ${c.HvapB} | ${c.rhoL} | ${c.Tc} |`).join('\n')}\n\n## Vapor-pressure source records\n\n${COMPONENTS.map(c=>`- ${c.name}, CAS ${c.cas}: ${c.source}`).join('\n')}\n\nSources: NIST Chemistry WebBook, Standard Reference Database 69. NIST's data-compilation attribution and terms remain applicable. This project does not claim NIST endorsement or ownership of the source database.\n`);
console.log(JSON.stringify({checks:checks.length,passed:checks.filter(c=>c.passed).length,iterations:r.iterations,diagnostics:r.diagnostics},null,2));
